### ISSUE TITLE
Decouple Logging

### ISSUE THREAD

**Issue by mkrebs81** [SmartGridready/SGrJava#56]
The published `commhandler4modbus` package ships with an implementation of Log4j, instead of just the SLF4J API.
This can cause conflicts when developing applications that use the library.

My workaround is like this:

```
implementation (group: 'ch.smartgridready', name: 'commhandler4modbus', version: "${sgrJavaVersion}") {
    exclude group: 'SGrJava.InterfaceFactory', module: 'emfEI4Modbus'
    exclude group: 'org.apache.logging.log4j', module: 'log4j-core'
    exclude group: 'org.apache.logging.log4j', module: 'log4j-api'
    exclude group: 'org.apache.logging.log4j', module: 'log4j-slf4j2-impl'
}
```

I suggest decoupling the logging framework from the library package.

**Comment by ergo-furrer** [comment]
I agree, we need to remove log4j from the implementations.
I plan it move the log4j dependencies to the 'testImplementation' to have the logs within the tests.

**Comment by mkrebs81** [comment]
I already modified the dependencies in the https://github.com/SmartGridready/SGrJava/tree/decouple-logging branch, so you can just merge it, if you like.
